name: pr approve

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: update file
        run: echo "$(date +%Y-%m-%dT%H:%M:%S)" >> test.txt
        
      - run: gh --version
        
      
