name: pr approve

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: update file
        run: echo "$(date +%Y-%m-%dT%H:%M:%S)" >> test.txt
        
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch -c $(date +%Y%m%d%H%M%S)
          git add .
          git commit -m 'Update file'
          gh pr create --title 'Update file'  --body 'aaa'
      
      
