name: approve & merge

on:
  pull_request:
    types:
      - opened

  workflow_dispatch:

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'foo/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --merge
